---
 - name: Playbook to install apache
   hosts: BloodThrone
   gather_facts: yes
   become: true
   tasks: 
    - name: Install apache httpd (state=present is optional)
      apt:
        name: apache2
        state: absent
