---

- name: Cisco OSPF example
  hosts: routers
  gather_facts: false

  tasks:
    - name:  provided OSPF V2 processes
      cisco.ios.ios_ospfv2:
        config:
         processes:
         - process_id: 500
           max_metric:
             router_lsa: true
             on_startup:
               time: 110
           areas:
           - area_id: '99'
             capability: true
             authentication:
               enable: true
           network:
             address: '192.168.2.0'
             wildcard_bits: '0.0.0.255'
             area: 99             
        state: merged



    - name: voisinage OSPF
      cisco.ios.ios_command:
        commands: show ip ospf nei
      register: output


    - name: print output
      debug:
        var: output.stdout_lines

